### PR TITLE
PopUp

### PR DESCRIPTION
**Pull request by melaniecasimiro**

### CODE REVIEW

**Review by drago20013 — CHANGES_REQUESTED** [review]
Move LoginConfirmation.tsx to /src/components/

**Comment by youssefalb** [comment]
This should be also a reusable component since it will be used in multiple places.
It will take some props and use them

**Comment by claude-perrin** [comment]
Rejected by technical reasons

**Review by AsserElfeki — CHANGES_REQUESTED** [review]
hey Melanie, 

it is a class component, it needs to be a functional component

**Comment by melaniecasimiro** [comment]
okay thank you, I'll correct it.

**Pull request closed without merging**
